# permissions for end users to view hackathormevents.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hackathormevent-viewer-role
rules:
- apiGroups:
  - event.hackathorm.org
  resources:
  - hackathormevents
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - event.hackathorm.org
  resources:
  - hackathormevents/status
  verbs:
  - get
