# permissions for end users to edit hackathormparticipants.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hackathormparticipant-editor-role
rules:
- apiGroups:
  - participant.hackathorm.org
  resources:
  - hackathormparticipants
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - participant.hackathorm.org
  resources:
  - hackathormparticipants/status
  verbs:
  - get
