
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - event.hackathorm.org
  resources:
  - hackathormevents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - event.hackathorm.org
  resources:
  - hackathormevents/finalizers
  verbs:
  - update
- apiGroups:
  - event.hackathorm.org
  resources:
  - hackathormevents/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - participant.hackathorm.org
  resources:
  - hackathormparticipants
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - participant.hackathorm.org
  resources:
  - hackathormparticipants/finalizers
  verbs:
  - update
- apiGroups:
  - participant.hackathorm.org
  resources:
  - hackathormparticipants/status
  verbs:
  - get
  - patch
  - update
